### ISSUE TITLE
How to submit solutions

### ISSUE THREAD

**Issue by Mohitgupta943** [SVCE-ACM/A-December-of-Algorithms#34]
I am new to git hub can you please guide me for submitting solutions.

**Comment by akashsara** [comment]
Check out this small tutorial to understand the basics of GitHub: https://guides.github.com/activities/hello-world/

For now, you need to simply code the solutions and push them to your fork of this repository. When you have finished all 31, then you can submit a pull request. We'll update the repository to show how to submit the pull request soon.
