### ISSUE TITLE
Question 31 Explanation

### ISSUE THREAD

**Issue by drstrange11** [SVCE-ACM/A-December-of-Algorithms#53]
I can't understand the explanation for the 2nd sample input in the question "closest cell" in Dec 31.
 "For this input program should return 2 because the closest cell (‘2’) is 2 spaces away from the ‘1’ by moving left to wrap to the other side and then moving down once",
Does it mean, moving left twice? Because 2 can be reached when you do that

**Comment by akashsara** [comment]
Good catch. It's meant to be moving left twice. I'll update it now.
